name: Release PR

on:
  workflow_dispatch:

jobs:
  create:
    name: "Create"
    runs-on: default-small
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: "main"
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .node-version
          registry-url: "https://npm.pkg.github.com"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pnpm install --frozen-lockfile
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pnpm build
          ./scripts/create-release-pr
